<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '新闻中心';
$typeArr[3] = '企业文化';
$typeArr[4] = '产品展示';
$typeArr[5] = '人才招聘';
$typeArr[6] = '在线留言';
$typeArr[7] = '联系我们';
$typeArr[12] = '发展历程';
$typeArr[13] = '企业前景';
$typeArr[14] = '公司简介';
$typeArr[15] = '企业展示';
$typeArr[16] = '行业新闻';
$typeArr[17] = '员工活动';
$typeArr[18] = '企业宗旨';
$typeArr[19] = '企业精神';
$typeArr[20] = '企业理念';
$typeArr[10] = '公司新闻';
$typeArr[21] = '企业文化';
$typeArr[22] = '经营理念';
$typeArr[23] = '联系我们';
$typeArr[24] = '销售网络';
?>