<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /lyyh/uploads/allimg/151108/1-15110QQ922.jpg ",93,258);
$z[1][4]['ddimg']="/lyyh/uploads/allimg/151108/1-15110QQ922.jpg";
$z[1][4]['text']="公司图片";
$z[1][4]['width']="722";
$z[1][4]['height']="385";

?>