
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="10" page="">
</field:name>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="30" page="">
</field:email>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="15" page="">
</field:tel>

<field:message itemname="留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:message>
