<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /lyyh/uploads/allimg/151110/1-1511101U153.jpg ",93,254);
$z[1][4]['ddimg']="/lyyh/uploads/allimg/151110/1-1511101U153.jpg";
$z[1][4]['text']="尾油";
$z[1][4]['width']="800";
$z[1][4]['height']="531";

?>