<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /lyyh/uploads/allimg/151109/1-1511091US3.jpg ",93,246);
$z[1][4]['ddimg']="/lyyh/uploads/allimg/151109/1-1511091US3.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="200";
$z[1][4]['height']="200";
$z[2]=Array("img"," /lyyh/uploads/allimg/151109/1-1511091US3-50.jpg ",248,407);
$z[2][4]['ddimg']="/lyyh/uploads/allimg/151109/1-1511091US3-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="200";
$z[2][4]['height']="200";
$z[3]=Array("img"," /lyyh/uploads/allimg/151109/1-1511091US3-51.jpg ",409,568);
$z[3][4]['ddimg']="/lyyh/uploads/allimg/151109/1-1511091US3-51.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="200";
$z[3][4]['height']="200";
$z[4]=Array("img"," /lyyh/uploads/allimg/151109/1-1511091US4.jpg ",570,723);
$z[4][4]['ddimg']="/lyyh/uploads/allimg/151109/1-1511091US4.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="200";
$z[4][4]['height']="200";

?>