
<field:style itemname="格式" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="avi,rmvb,mp4,flv"  maxlength="250" page="">
</field:style>

<field:lifetime itemname="时长" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="0"  maxlength="250" page="">
</field:lifetime>

<field:from itemname="来源" autofield="1" notsend="0" type="media" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:from>

