<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /lyyh/uploads/allimg/151109/1-151109195423.jpg ",93,265);
$z[1][4]['ddimg']="/lyyh/uploads/allimg/151109/1-151109195423.jpg";
$z[1][4]['text']="液化石油气";
$z[1][4]['width']="300";
$z[1][4]['height']="327";

?>