<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",200,302);
$z[2]=Array("include","",380,419);
$z[2][4]['filename']="contact.html";
$z[3]=Array("field","",529,551);
$z[3][4]['name']="typename";
$z[4]=Array("field","",586,615);
$z[4][4]['name']="position";
$z[5]=Array("field","",818,839);
$z[5][4]['name']="content";
$z[6]=Array("include","",1641,1678);
$z[6][4]['filename']="footer.htm";

?>