<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",192,294);
$z[2]=Array("include","",352,391);
$z[2][4]['filename']="contact.html";
$z[3]=Array("field","",501,523);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",558,587);
$z[4][4]['name']="position";
$z[5]=Array("arclist","\r\n            <li>\r\n           <a  href=\"[field:arcurl/]\">[field:description/]</a>[field:pubdate function=MyDate('Y.m.d',@me)/]<br/>\r\n           </li>\r\n           ",718,951);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="24";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("include","",1063,1100);
$z[6][4]['filename']="footer.htm";

?>