<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",415,447);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\n            <li>[field:textlink/][field:pubdate function=MyDate('Y/m/d',@me)/]</li>\n             ",1124,1307);
$z[2][4]['row']="10";
$z[2][4]['titlelen']="24";
$z[2][4]['orderby']="pubdate";
$z[2][4]['typeid']="10,16";
$z[3]=Array("global","",2208,2240);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2976,3008);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",3217,3249);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",3444,3476);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("channelartlist","\n\n            <li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\n\n\n            ",3727,3889);
$z[7][4]['typeid']="3";
$z[8]=Array("arclist","\n		<dl>\n		<dt>[field:imglink/]</dt>\n		\n		<dd>[field:textlink/]</dd>\n		</dl>\n		",4170,4359);
$z[8][4]['row']="10";
$z[8][4]['titlelen']="24";
$z[8][4]['orderby']="pubdate";
$z[8][4]['typeid']="4";
$z[8][4]['idlist']="";
$z[8][4]['col']="1";
$z[8][4]['limit']="0,2";
$z[9]=Array("include","",4895,4932);
$z[9][4]['filename']="footer.htm";

?>