<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",201,303);
$z[2]=Array("include","",363,402);
$z[2][4]['filename']="contact.html";
$z[3]=Array("field","",512,534);
$z[3][4]['name']="typename";
$z[4]=Array("field","",569,598);
$z[4][4]['name']="position";
$z[5]=Array("field","",729,750);
$z[5][4]['name']="content";
$z[6]=Array("include","",843,880);
$z[6][4]['filename']="footer.htm";

?>