<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",170,202);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("field","",761,783);
$z[2][4]['name']="typename";
$z[3]=Array("field","",817,839);
$z[3][4]['name']="position";
$z[4]=Array("global","",973,1005);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",1095,1132);
$z[5][4]['filename']="footer.htm";

?>