<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("sonchannel","\r\n			<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n			",181,283);
$z[2]=Array("include","",341,380);
$z[2][4]['filename']="contact.html";
$z[3]=Array("field","",479,501);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",533,562);
$z[4][4]['name']="position";
$z[5]=Array("field","",644,665);
$z[5][4]['name']="content";
$z[6]=Array("include","",797,834);
$z[6][4]['filename']="footer.htm";

?>