<?php
$z[0]=Array("include","",32,67);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channelartlist","\r\n 			<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n			",176,320);
$z[1][4]['typeid']="2";
$z[2]=Array("global","",370,402);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",958,980);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1011,1033);
$z[4][4]['name']="position";
$z[5]=Array("arclist","\r\n\r\n<table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n  <tbody><tr> \r\n    <td width=\"30%\" rowspan=\"2\" align=\"center\">[field:imglink/]</td>\r\n    <td width=\"70%\"><a href=\"[field:filename/]\">[field:title/]</a></td>\r\n  </tr>\r\n  <tr><td>[field:info/]</td></tr>\r\n</tbody></table>\r\n\r\n",1153,1537);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="24";
$z[5][4]['orderby']="pubdate";
$z[5][4]['typeid']="10";
$z[5][4]['idlist']="";
$z[6]=Array("include","",1719,1756);
$z[6][4]['filename']="footer.htm";

?>