<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channelartlist","\r\n 			<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n			",169,313);
$z[1][4]['typeid']="2";
$z[2]=Array("global","",347,379);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",938,960);
$z[3][4]['name']="typename";
$z[4]=Array("field","",995,1024);
$z[4][4]['name']="position";
$z[5]=Array("arclist","\r\n			<dl>\r\n                 <dt>[field:imglink/]</dt>\r\n                 <dd>[field:textlink/]</dd>\r\n            </dl> \r\n            ",1128,1330);
$z[5][4]['titlelen']="24";
$z[5][4]['typeid']="17";
$z[5][4]['channelid']="2";
$z[6]=Array("include","",1486,1523);
$z[6][4]['filename']="footer.htm";

?>