<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channelartlist","\r\n 			<li><a href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a></li>\r\n			",165,309);
$z[1][4]['typeid']="7";
$z[2]=Array("include","",367,406);
$z[2][4]['filename']="contact.html";
$z[3]=Array("field","",516,538);
$z[3][4]['name']="typename";
$z[4]=Array("field","",573,602);
$z[4][4]['name']="position";
$z[5]=Array("field","",733,754);
$z[5][4]['name']="content";
$z[6]=Array("include","",847,884);
$z[6][4]['filename']="footer.htm";

?>