<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",184,223);
$z[1][4]['filename']="contact.html";
$z[2]=Array("field","",333,355);
$z[2][4]['name']="typename";
$z[3]=Array("field","",390,419);
$z[3][4]['name']="position";
$z[4]=Array("arclist","\r\n			<dl>\r\n                 <dt>[field:imglink/]</dt>\r\n                 <dd>[field:textlink/]</dd>\r\n            </dl> \r\n            ",523,724);
$z[4][4]['titlelen']="24";
$z[4][4]['typeid']="4";
$z[4][4]['channelid']="2";
$z[5]=Array("include","",880,917);
$z[5][4]['filename']="footer.htm";

?>