<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",194,233);
$z[1][4]['filename']="contact.html";
$z[2]=Array("field","",343,365);
$z[2][4]['name']="typename";
$z[3]=Array("field","",400,429);
$z[3][4]['name']="position";
$z[4]=Array("field","",506,527);
$z[4][4]['name']="content";
$z[5]=Array("include","",597,634);
$z[5][4]['filename']="footer.htm";

?>