<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",49,81);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",224,279);
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("likewords","",423,448);
$z[3][4]['num']="8";
$z[4]=Array("global","",510,535);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("list","\r\n				<li>      				\r\n					<h3><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h3>\r\n                    <p>[field:description/]...</p>\r\n					<span>\r\n					    <a href=\"[field:arcurl/]\">[field:global.cfg_basehost/][field:arcurl/]</a>\r\n						<small>分类：</small><a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a>\r\n						<small>点击：</small>[field:click/]\r\n						<small>日期：</small>[field:stime/]\r\n					</span>\r\n				</li>\r\n			",660,1159);
$z[5][4]['perpage']="20";
$z[6]=Array("pagelist","",1242,1271);
$z[6][4]['listsize']="4";
$z[7]=Array("include","",1345,1382);
$z[7][4]['filename']="footer.htm";

?>